from __future__ import annotations

from pydantic import BaseModel, Field


class RecommendedAction(BaseModel):
    """Structured retention action generated by the LLM."""

    action: str = Field(min_length=1)
    details: str = Field(min_length=1)


class PolicyRationale(BaseModel):
    """Business policy evidence supporting the recommendation."""

    source: str = Field(min_length=1)
    section: str = Field(min_length=1)
    reason: str = Field(min_length=1)


class RetentionRecommendation(BaseModel):
    """Validated LLM-generated retention recommendation."""

    customer_id: int
    risk_summary: str = Field(min_length=1)
    recommended_action: RecommendedAction
    secondary_consideration: str = Field(min_length=1)
    supporting_evidence: list[str]
    policy_rationale: list[PolicyRationale]
    guardrails: list[str]